시작페이지 및 모달 제작
project-MAT/MAT-front pull request #8
Opened 2022-02-09 02:41 UTC by JYG0326

2022-02-09 12:35 UTC, yoosion030 requested changes
css 파일이 지금 Modals 폴더에 바로 있어서 로그인 모달이랑 회원가입 스타일이 한 파일안에 다 있잖아 그게 아니라 LoginMoadl 폴더에 하나 RegisterModal에 하나씩 css 파일을 만들면 좋을 것 같아 

![image](https://user-images.githubusercontent.com/80191860/153202159-95e3ea82-13a1-4608-ab23-81d70830facb.png)

2022-02-09 12:46 UTC, yoosion030 reviewed
![image](https://user-images.githubusercontent.com/80191860/153203774-b70194eb-7bd1-4dbc-8986-1f5119688171.png)
![image](https://user-images.githubusercontent.com/80191860/153203801-acc1bcdb-be34-41d0-a00b-a3c8661b382b.png)

반응형 했을 때 회원가입이 로그인을 가려서 나중에는 로그인이 안보여 ㅠㅠ 이거 확인해주라 !!

2022-02-09 12:46 UTC, yoosion030 commented on src/Components/Modals/RegisterModal/index.js
> +class RegisterModal extends Component {
Class 컴포넌트형 보다 함수형 컴포넌트로 만드는게 보기 좋을 것 같아!

2022-02-09 12:46 UTC, yoosion030 commented on src/Components/Modals/RegisterModal/index.js
> +          <input name="discordNum" className="modalinput" type="text" placeholder=" 디스코드 고유번호(#제외)를 입력하세요" onChange={this.handleInput} />
![image](https://user-images.githubusercontent.com/80191860/153202989-8d375436-0a41-4357-86cb-eb9917237bb1.png)
이부분이 너무 길어서 내용이 다 안보여

2022-02-09 12:46 UTC, yoosion030 commented on src/Components/Start/style.css
> +}
이런 공통된 스타일들은 index.css 에 추가하는게 좋을 것 같아

2022-02-09 12:47 UTC, yoosion030 requested changes
![image](https://user-images.githubusercontent.com/80191860/153203774-b70194eb-7bd1-4dbc-8986-1f5119688171.png)
![image](https://user-images.githubusercontent.com/80191860/153203801-acc1bcdb-be34-41d0-a00b-a3c8661b382b.png)

반응형 했을 때 회원가입이 로그인을 가려서 나중에는 로그인이 안보여 ㅠㅠ 이거 확인해주라 !!

2022-02-09 13:49 UTC, JYG0326 commented on src/Components/Modals/RegisterModal/index.js
> +class RegisterModal extends Component {
함수형 컴포넌트는 api연결이나 토큰 받아오는 기능들이 클래스형으로 묶여 있어서 당장 변경은 좀 어려울거같고 일단은 우선순위로 고려해둘게

2022-02-09 13:49 UTC, JYG0326 commented on src/Components/Modals/RegisterModal/index.js
> +          <input name="discordNum" className="modalinput" type="text" placeholder=" 디스코드 고유번호(#제외)를 입력하세요" onChange={this.handleInput} />
input 내부 폰트 크기 축소시켜서 해결할게

2022-02-09 13:50 UTC, JYG0326 commented on src/Components/Start/style.css
> +}
알았어 반영해둘게

2022-02-09 14:20 UTC, JYG0326 commented
코드리뷰 한거 컴포넌트형 관련한거 제외하고 나머지 요청사항들 반영해서 커밋했으니까 한번 봐주고 문제 없으면 머지 시켜줘!

2022-02-09 14:49 UTC, yoosion030 commented on src/Components/Modals/RegisterModal/index.js
> +class RegisterModal extends Component {
아하 일단 알겠어

2022-02-10 15:07 UTC, yoosion030 approved these changes

2022-02-10 15:07 UTC, yoosion030 commented on src/index.css
> +
디자인 다시 봐봤는데 font가 `font-family: Rounded Mplus 1c Bold;`로 바꼈더라구
```suggestion
@import url('https://fonts.googleapis.com/css2?family=Hahmlet:wght@700&family=Noto+Sans+KR:wght@700&display=swap');
*{
    font-family: Rounded Mplus 1c Bold;
}

```
**Add suggestion to batch** 누르면 바로 적용되니까 적용시켜주라

2022-02-10 15:07 UTC, merged